services:
  - type: web
    name: voter-backend
    env: python
    buildCommand: pip install --no-cache-dir -r requirements.txt
    startCommand: gunicorn app:app
    plan: free  # Or choose a paid plan if needed
    autoDeploy: true
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
      - key: SECRET_KEY
        value: some-secret-key  # Replace with your actual secret
      - key: EXCEL_FILE
        value: VOTE.xlsx
